# Generated by Django 3.2.4 on 2021-07-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
